ibra/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('masta/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    # path('blog/', include('blog.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, include
from . import checkviews
from . import views

urlpatterns = [
    # path('addoneproduct', views.addoneproduct, name='addoneproduct'),
    # path('addoneproduct', views.addoneproduct, name='addoneproduct'),
    # path('addoneproduct', views.addoneproduct, name='addoneproduct'),
    # path('addoneproduct', views.addoneproduct, name='addoneproduct'),
    # path('addoneproduct', views.addoneproduct, name='addoneproduct'),
    # path('addoneproduct', views.addoneproduct, name='addoneproduct'),
    path('promotionspage', views.promotionspage, name='promotionspage'),
    path('b3921b/minidashboard', views.minidashboard, name='minidashboard'),
    path('allowcatalog', views.allowcatalog, name='allowcatalog'),
    path('notifyadmin', views.notifyadmin, name='notifyadmin'),
    path('disablenotif', views.disablenotif, name='disablenotif'),
    path('getconnectedusers', views.getconnectedusers, name='getconnectedusers'),
    path('updatepdctdata', views.updatepdctdata, name='updatepdctdata'),
    path('listeconnected', views.listeconnected, name='listeconnected'),
    path('addoneproduct', views.addoneproduct, name='addoneproduct'),
    path('updateproduct', views.updateproduct, name='updateproduct'),
    path('addclient', views.addclient, name='addclient'),
    path('createclientaccount', views.createclientaccount, name='createclientaccount'),
    path('deactivateaccount', views.deactivateaccount, name='deactivateaccount'),
    path('activateaccount', views.activateaccount, name='activateaccount'),
    path('createnewclientaccount', views.createnewclientaccount, name='createnewclientaccount'),
    path('updateclient', views.updateclient, name='updateclient'),
    path('activerproduct', views.activerproduct, name='activerproduct'),
    path('desactiverproduct', views.desactiverproduct, name='desactiverproduct'),
    path('addcommercial', views.addcommercial, name='addcommercial'),
    path('createcategory', views.createcategory, name='createcategory'),
    path('updatecategory', views.updatecategory, name='updatecategory'),
    path('createmarque', views.createmarque, name='createmarque'),
    path('updatemarque', views.updatemarque, name='updatemarque'),
    path('createpromotion', views.createpromotion, name='createpromotion'),
    path('updatepromotion', views.updatepromotion, name='updatepromotion'),
    path('getcarts', views.getcarts, name='getcarts'),
    path('getwishs', views.getwishs, name='getwishs'),
    path('addnotification', views.addnotification, name='addnotification'),
    path('updatenotification', views.updatenotification, name='updatenotification'),
    path('createnewrepaccount', views.createnewrepaccount, name='createnewrepaccount'),
    path('searchclientrep', views.searchclientrep, name='searchclientrep'),
    path('refspage', views.refspage, name='refspage'),
    path('updaterepdata', views.updaterepdata, name='updaterepdata'),
    path('relevclient', views.relevclient, name='relevclient'),
    path('relevclientfc', views.relevclientfc, name='relevclientfc'),
    path('createrepaccount', views.createrepaccount, name='createrepaccount'),
    path('sendcommandstoserver', views.sendcommandstoserver, name='sendcommandstoserver'),
    path('getcommandnumber', views.getcommandnumber, name='getcommandnumber'),
    path('updatestockfromthread', views.updatestockfromthread, name='updatestockfromthread'),
    path('createlogo', views.createlogo, name='createlogo'),
    # path('addoneproduct', views.addoneproduct, name='addoneproduct'),
    # path('addoneproduct', views.addoneproduct, name='addoneproduct'),
    # path('addoneproduct', views.addoneproduct, name='addoneproduct'),
    # path('addoneproduct', views.addoneproduct, name='addoneproduct'),
    # path('addoneproduct', views.addoneproduct, name='addoneproduct'),
    # path('addoneproduct', views.addoneproduct, name='addoneproduct'),
    # path('addoneproduct', views.addoneproduct, name='addoneproduct'),
]

products/models.py
from django.db import models

# Create your models here.

products/views.py
from django.shortcuts import render, redirect
from main.models import Produit, Mark, Category, Supplier, Stockin, Itemsbysupplier, Client, Represent, Order, Orderitem, Clientprices, Bonlivraison, Facture, Outfacture, Livraisonitem, PaymentClientbl, PaymentClientfc,  PaymentSupplier, Bonsregle, Returnedsupplier, Avoirclient, Returned, Avoirsupplier, Orderitem, Carlogos, Ordersnotif, Connectedusers, Promotion, UserSession, Refstats, Notavailable, Cart, Wishlist, Wich, Notification, Cartitems
from django.contrib.auth import logout
from django.http import JsonResponse, HttpResponse
import openpyxl
# import Count
from django.contrib.auth.models import User
from django.db.models import Count, F, Sum, Q, ExpressionWrapper, Func, fields, IntegerField
from django.db.models.functions import Cast
from django.contrib.sessions.models import Session
from functools import wraps
from django.contrib.auth.decorators import user_passes_test
import json
from django.contrib.auth.models import Group
from django.db import transaction
from datetime import datetime, date, timedelta
from django.utils import timezone
import pandas as pd
from itertools import chain
from django.core.serializers import serialize
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
today = timezone.now().date()
thisyear=timezone.now().year
import requests as req

def isadmin(user):
    if not user.groups.filter(name='admin').exists():
        redirect('main:logoutuser')

# call isadmin here so that it executes before executing all the views

def getproductsbycategory(request):
    # category = Category.objects.get(pk=request.POST.get('category'))
    # products = category.product.filter(category=category)[:10]
    # get ten products from the category
    products = Produit.objects.filter(category__pk=request.POST.get('category')).order_by('code')
    # get marks of the products filtered
    marks = Mark.objects.filter(produit__in=products).distinct().annotate(count=Count('produit'))
    ctx={
        'products':products,
        'home':False,
        'marks':marks,

    }
    return JsonResponse({
        'data':render(request, 'product_search.html', ctx).content.decode('utf-8'),
        'stocktotal':products.aggregate(Sum('stocktotal'))['stocktotal__sum'] or 0,
        'stockfacture':products.aggregate(Sum('stockfacture'))['stockfacture__sum'] or 0,
    })

def adminaddproductpage(request):
    categories=Category.objects.all()
    marques=Mark.objects.all()
    ctx={'categories':categories,
         'marques':marques,
         'commercials':Represent.objects.all(),
         'carlogos':Carlogos.objects.all(),
        }
    return render(request, 'addproduct.html', ctx)



def categoriespage(request):
    ctx={
        'categories':Category.objects.all().order_by('code'),
        'commercials':Represent.objects.all(),
        'title':'Categories'
    }
    return render(request, 'categories.html', ctx)
@csrf_exempt
def createcategory(request):
    print('>>>>>>>> creating category')
    name=request.POST.get('name')
    code=request.POST.get('code')
    affichage=request.POST.get('affichage')
    hideclient=request.POST.get('hideclient')=='True'
    commercialexcluded=request.POST.getlist('commercialexcluded')
    reps=Represent.objects.filter(pk__in=commercialexcluded)
    print(len(commercialexcluded)>0)

    # get image file
    image = request.FILES.get('image')
    # create category
    category=Category.objects.create(name=name, image=image, code=code, affichage=affichage, masqueclients=hideclient)
    if len(commercialexcluded)>0:
        print('getting reps', commercialexcluded, reps)
        category.excludedrep.set(reps)
    return JsonResponse({
        'success':True
    })
@csrf_exempt
def updatecategory(request):
    
    id=request.POST.get('id')
    hideclient=request.POST.get('hideclient')
    commercialexcluded=request.POST.getlist('commercialexcluded')
    reps=Represent.objects.filter(pk__in=commercialexcluded)
    category=Category.objects.get(pk=id)
    category.masqueclients=hideclient
    category.excludedrep.clear()
    category.excludedrep.set(reps)
    category.name=request.POST.get('name')
    category.affichage=request.POST.get('affichage')
    category.code=request.POST.get('code')
    image=request.FILES.get('image')
    if image:
        category.image=image
    category.save()
    return JsonResponse({
        'success':True
    })


@csrf_exempt
def createmarque(request):
    try:
        name=request.POST.get('name')
        # get image file
        image=request.FILES.get('image')
        # create category
        hideclient=request.POST.get('hideclient')
        commercialexcluded=request.POST.getlist('commercialexcluded')
        reps=Represent.objects.filter(pk__in=commercialexcluded)
        print(hideclient, commercialexcluded, reps)
        mrq=Mark.objects.create(name=name, image=image, masqueclients=hideclient)
        mrq.excludedrep.set(reps)
        return JsonResponse({
            'success':True
        })
    except Exception as e:
        print(">>>>>error", e)
@csrf_exempt
def updatemarque(request):

    id=request.POST.get('id')
    print('>>>>>> updating mark', id)
    try:
        image=request.FILES.get('image')
        hideclient=request.POST.get('hideclient')
        commercialexcluded=request.POST.getlist('commercialexcluded')
        reps=Represent.objects.filter(pk__in=commercialexcluded)
        mark=Mark.objects.get(pk=id)
        mark.name=request.POST.get('name')
        mark.masqueclients=hideclient
        mark.excludedrep.clear()
        mark.excludedrep.set(reps)
        if image:
            mark.image=image
        mark.save()
        
        return JsonResponse({
            'success':True
        })
    except Exception as e:
        print(">>>>", e)

def checkref(request):
    ref=request.POST.get('ref').lower().strip()
    product=Produit.objects.filter(ref=ref)
    print(ref)
    if product:
        return JsonResponse({
            'exist':True
        })
    return JsonResponse({
        'exist':False
    })

    # print(ref, category, product)
    # if product:
    # else:
    #     return JsonResponse({
    #         'exist':False
    #     })

def supplierspage(request):
    ctx={
        'suppliers':Supplier.objects.all(),
        'title':'List des fournisseurs'
    }
    return render(request, 'suppliers.html', ctx)

def getsupplierdata(request):
    id=request.POST.get('id')
    supplier=Supplier.objects.get(pk=id)
    return JsonResponse({
        'name':supplier.name,
        'phone':supplier.phone,
        'address':supplier.address,
        'id':supplier.id
    })


def updatesupplier(request):
    id=request.POST.get('pid')
    name=request.POST.get('pname')
    phone=request.POST.get('pphone')
    address=request.POST.get('paddress')
    supplier=Supplier.objects.get(pk=id)
    supplier.name=name
    supplier.phone=phone
    supplier.address=address
    supplier.save()
    ctx={
        'suppliers':Supplier.objects.all(),
        'title':'List des fournisseurs'
    }
    return JsonResponse({
        'html':render(request, 'suppliers.html', ctx).content.decode('utf-8')
    })

def addoneproduct(request):
    try:
        ref=request.GET.get('ref').lower().strip()
        name=request.GET.get('name').strip()
        uniqcode=request.GET.get('uniqcode')
        category=request.GET.get('category')
        commercialsprix=request.GET.get('commercialsprix') or "[]"
        mark=request.GET.get('mark') or None
        logo=request.GET.get('logo', None)
        image=request.GET.get('image')
        sellprice=request.GET.get('sellprice') or 0
        supplier=request.GET.get('supplier') or None
        minstock=request.GET.get('minstock') or 0
        buyprice=request.GET.get('buyprice') or 0
        remise=request.GET.get('remise') or 0
        diametre=request.GET.get('diametre') or ''
        representprice=request.GET.get('repprice') or None
        code=request.GET.get('code') or '00'
        block=request.GET.get('block') or ''
        equivalent=request.GET.get('equiv') or ''
        cars=request.GET.getlist('cars') or ''
        print('>>>>>>>', image)
        netprice=round(float(sellprice)-(float(sellprice)*float(remise)/100), 2)
        # create product
        print('>>>>>>>>>>>>>>>creating product')
        Produit.objects.create(
            ref=ref,
            name=name,
            buyprice=buyprice,
            diametre=diametre,
            sellprice=sellprice,
            remise=remise,
            prixnet=netprice,
            representprice=representprice,
            minstock=minstock,
            equivalent=equivalent,
            cars=cars,
            category_id=category,
            supplier_id=supplier,
            mark_id=mark,
            image=image,
            uniqcode=uniqcode,
            code=code,
            repsprice=commercialsprix,
            block=block,
            stocktotal=0,
            stockfacture=0,
            isactive=True
        )

        
        return JsonResponse({
            'success':True,
        })
    except Exception as e:
        print(e)
        return JsonResponse({
            'error':e
        })


def viewoneproduct(request, id):
    product=Produit.objects.get(pk=id)
    commercial_prices = product.getcommercialsprice()  # Note the parentheses ()
    stockin=Stockin.objects.filter(product=product)
    outbl=Livraisonitem.objects.filter(product=product, isfacture=False).aggregate(Sum('qty'))['qty__sum'] or 0
    outfacture=Outfacture.objects.filter(product=product).aggregate(Sum('qty'))['qty__sum'] or 0
    revbl=Livraisonitem.objects.filter(product=product, isfacture=False).aggregate(Sum('total'))['total__sum'] or 0
    revfacture=Outfacture.objects.filter(product=product).aggregate(Sum('total'))['total__sum'] or 0
    totalout=outbl+outfacture
    totalrev=round(revbl+revfacture, 2)
    print(totalrev)

products/templates/promotions.html
<div class="card">
    <h5 class="card-header">{{title}}</h5>

    <div class="card-body row">
        <div class="col-3">
            <div class="border-end p-2">
                <strong>
                    + Ajouter une promotion
                </strong>
                <form class="mt-3" method="post" enctype="multipart/form-data" id="createpromotion">
                    {% csrf_token %}
                    <input name="promotionname" type="text" class="form-control mb-2" placeholder="promotion" required>
                    <strong>Image</strong>
                    <input name="promotionimage" type="file" class="form-control" required>
                    <button class="btn btn-primary w-100 mt-2 createpromotionbtn">Ajouter</button>
                </form>
            </div>
        </div>
        <div class="col-9">
            <input type="text" class="form-control" placeholder="Chercher" id="searchbox">
            <div class="bg-white border p-2">
                <div class="row">
                    {% for i in promotions %}
                    <div class="col-4 mb-2 searchcardspromotion">
                        <p hidden>
                            {{i.info}}
                        </p>
                        <div class="border-end p-2">
                            <form action="{% url 'products:updatepromotion' %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input type="hidden" name="id" value="{{i.id}}">
                                {{i.id}}
                                {% if i.image %}
                                <img class="text-center w-100" src="{{i.image.url}}" alt="">
                                {% endif %}
                                <input type="file" name="image" class="form-control">
                                <input type="text" name="name" class="form-control" value="{{i.info}}">
                                <button class="btn btn-sm w-100 updatepromotionbtn">Mise à jour</button>
                            </form>
                        </div>
                    </div>
                        {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $('.updatepromotionbtn').on('click', function(event){
        event.preventDefault()
        name=$(event.target).parent().find('input')[3]
        id=$(event.target).attr('id')
        form=$(event.target).parent()
        name=$($(event.target).parent().find('input')[3]).val()
        if ($(name).val()==""){
            name.css('border', '1px solid red')
            return
        }
        var formData = new FormData($(event.target).parent()[0]);
	    console.log('>> formData', formData)
	    $.ajax({
            type: 'POST',
            url: '{% url "products:updatepromotion" %}',  // Replace with your Django URL
            data: formData,
            processData: false,
            contentType: false,
            success:((data)=>{
                updatetab('promotionstab', '/products/promotionspage')
            })
        })
        
    
    })
    $('.createpromotionbtn').on('click', function(event){
        event.preventDefault()
        console.log('sending')
        if ($('[name="promotionname"]').val()=="" || $('[name="promotionimage"]').val()==""){
            $('#createpromotion').css('border', '1px solid red')
            return
        }
        var formData = new FormData($('#createpromotion')[0]);

        $.ajax({
            type: 'POST',
            url: '{% url "products:createpromotion" %}',  // Replace with your Django URL
            data: formData,
            processData: false,
            contentType: false,
            success:((data)=>{
                updatetab('promotionstab', '/products/promotionspage')
            })
        })
    })
</script>

products/templates/refspage.html
		{% for i in refs %}
		<tr>
			<td>
				{{i.lastdate|date:'d/m/Y'}}
			</td>
			<td>
				{{i.ref}}
			</td>
			<td>
				{{i.times}}
			</td>
			<td>
				{{i.user.client.name}}{{i.user.represent.name}}
			</td>
			<td> <button class="btn btn-danger" onclick="deletsearchedref(event, '{{i.id}}')">X</button> </td>
		</tr>
		{% endfor %}
<script>
	function deletsearchedref(event, refid){
		$.get('/products/deletsearchedrefserver', {
			'refid':refid
		}, (data)=>{
			$(event.target).parent().parent().remove()
		})
	}
</script>