ibra/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('masta/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    # path('blog/', include('blog.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from django.views.defaults import page_not_found
urlpatterns = [
    path('', views.home, name='home'),
    path('product/<int:id>', views.product, name='product'),
    path('clientdashboar', views.clientdashboar, name='clientdashboar'),
    path('searchref', views.searchref, name='searchref'),
    path('commande', views.commande, name='commande'),
    path('orders', views.orders, name='orders'),
    path('orderitems/<int:id>', views.orderitems),
    path('dilevered/<int:id>', views.dilevered),
    path('paied/<int:id>', views.paied),
    path('marks/products/<int:id>', views.products),
    path('categories/products/<int:id>', views.productscategories),
    path('marques/products/<int:id>', views.productsmarks),
    path('login', views.loginpage, name='loginpage'),
    path('ibra', views.ibra, name='ibra'),
    path('catalog', views.catalog, name='catalog'),
    path('salsemanorders/<str:str_id>', views.salsemanorders, name='salsemanorders'),
    path('logoutuser', views.logoutuser, name='logoutuser'),
    path('clients', views.clients, name='clients'),
    path('addclient', views.addclient, name='addclient'),
    path('aboutus', views.aboutus, name='aboutus'),
    path('partners', views.partners, name='marques'),
    path('profile', views.profile, name='profile'),
    path('editinfoclient', views.editinfoclient, name='editinfoclient'),
    path('updatepassword', views.updatepassword, name='updatepassword'),
    path('developer', views.developer, name='developer'),
    path('cart', views.cart, name='cart'),
    path('ordersforeach', views.ordersforeach, name='ordersforeach'),
    path('sitemap', views.sitemap, name='sitemap'),
    path('makeuserconnected', views.makeuserconnected, name='makeuserconnected'),
    path('loginuser', views.loginuser, name='login'),
    path('catalogpage', views.catalogpage, name='catalogpage'),
    path('client/clientshome', views.clientshome, name='clientshome'),
    path('client/searchglobal', views.searchglobal, name='searchglobal'),
    path('productdata', views.productdata, name='productdata'),
    path('searchrefphone', views.searchrefphone, name='searchrefphone'),
    path('addtocart', views.addtocart, name='addtocart'),
    path('removeitemfromcart', views.removeitemfromcart, name='removeitemfromcart'),
    path('removecart', views.removecart, name='removecart'),
    path('getitemsincart', views.getitemsincart, name='getitemsincart'),
    path('addtowhishlist', views.addtowhishlist, name='addtowhishlist'),
    path('updatecartitem', views.updatecartitem, name='updatecartitem'),
    path('updatewishitem', views.updatewishitem, name='updatewishitem'),
    path('getitemsincart', views.getitemsincart, name='getitemsincart'),
    path('getitemsinwishlist', views.getitemsinwishlist, name='getitemsinwishlist'),
    path('removeitemfromwish', views.removeitemfromwish, name='removeitemfromwish'),
    path('switchtocart', views.switchtocart, name='switchtocart'),
    path('replicata', views.replicata, name='replicata'),
    path('notifications', views.notifications, name='notifications'),
    path('catalogpermission', views.catalogpermission, name='catalogpermission'),
    path('newarrivage', views.newarrivage, name='newarrivage'),
    path('allproducts', views.allproducts, name='allproducts'),
    path('B152242/AZEDurtghh/LK1225Kll/84522KLMM', views.ordersnotsent, name='ordersnotsent'),
    path('sendordertoserver', views.sendordertoserver, name='sendordertoserver'),
    path('workingclient', views.workingclient, name='workingclient'),
    path('relveclientforrep', views.relveclientforrep, name='relveclientforrep'),
    path('getproducdataforsuppliers', views.getproducdataforsuppliers, name='getproducdataforsuppliers'),
    path('makecommandnotsent', views.makecommandnotsent, name='makecommandnotsent'),
    # path('clientshome', views.clientshome, name='clientshome'),
    # path('clientshome', views.clientshome, name='clientshome'),
    # path('clientshome', views.clientshome, name='clientshome'),
    # path('clientshome', views.clientshome, name='clientshome'),
    # path('clientshome', views.clientshome, name='clientshome'),
    # path('clientshome', views.clientshome, name='clientshome'),
]

ibra/templates/baseaccount.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i" rel="stylesheet" />

    <link href="{% static 'css/bootstrap.css' %} " rel="stylesheet" />
    <link href="{% static 'css/style.css'%} " rel="stylesheet" />

</head>
<body>
    <div class="site__body">
        <div class="block-space block-space--layout--after-header"></div>
        <div class="block">
            <div class="container container--max--xl">
                <div class="row">
                    <div class="col-12 col-lg-3 d-flex">
                        <div class="account-nav flex-grow-1">
                            <h4 class="account-nav__title">Navigation</h4>
                            <ul class="account-nav__list">
                                <li class="account-nav__item"><a href="{% url 'home' %}">Store</a></li>
                                <li class="account-nav__item"><a href="{% url 'account' %}">Dashboard</a></li>
                                <li class="account-nav__item"><a href="{% url 'garage' %}">Garage</a></li>
                                <li class="account-nav__item"><a href="{% url 'editprofile' %}">Edit Profile</a></li>
                                <li class="account-nav__item"><a href="{% url 'orders' %}">Order
                                        History</a></li>
                                <li class="account-nav__item"><a href="{% url 'password' %}">Password</a></li>
                                <li class="account-nav__divider" role="presentation"></li>
                                <li class="account-nav__item"><a href="">Logout</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-12 col-lg-9 mt-4 mt-lg-0">
                        
                            {% block content %}
                            {% endblock %}
                    </div>
                </div>
            </div>
        </div>
        <div class="block-space block-space--layout--before-footer"></div>
    </div>
    
    <div class="site-footer__bottom">
        <div class="container">
            <div class="site-footer__bottom-row">
                <div class="site-footer__copyright">
                    <!-- copyright --> Powered by HTML — Designed by <a href="https://themeforest.net/user/kos9"
                        target="_blank">Kos</a><!-- copyright / end -->
                </div>
                <div class="site-footer__payments"><img src="images/payments.png" alt=""></div>
            </div>
        </div>
    </div>
</body>
</html>

ibra/templates/me.html
{% extends 'base.html' %}

{% load static %}
{% block css %}
{% endblock %}

{% block content %}

<div class="row justify-content-center align-items-center mt-3">
  <div class="card col-5">
    <h5 class="card-header">Abdelwahed ait ali</h5>
    <div class="card-body">
      <h5 class="card-title">06 28 59 92 49</h5>
      <p class="card-text">aitaliabdelwahed@gmail.com</p>
    </div>
  </div>
</div>

{% endblock %}

ibra/templates/mobileheader.html
<header class="site__mobile-header repheader">
    <div class="mobile-header bg-darkblue">

      <div class="mobile-header__body">
      <!-- <button class="btn displayrepheader text-white" onclick="$('.repheader').css('top', '-50em')">X</button> -->

        {% if user.groups.all.0.name != 'accounting' %}
        <button class="mobile-header__menu-button" type="button">
          <svg width="18px" height="14px"><path d="M-0,8L-0,6L18,6L18,8L-0,8ZM-0,-0L18,-0L18,2L-0,2L-0,-0ZM14,14L-0,14L-0,12L14,12L14,14Z"></path></svg>
        </button>
        {% endif %}
        {% if user.groups.all.0.name == 'salsemen' %}
        <a class="btn btn-sm bg-orange text-white me-2 bi bi-house" href="/catalogpage" target="_blank"></a>



        {% endif %}
        {% if user.groups.all.0.name != 'accounting' %}
        <div class="mobile-header__search mobile-search d-sm-none d-md-block flex-column m-auto">
          <div class="mobile-search__body">
            <input type="text" class="mobile-search__input searchphone search__input" placeholder="Enter keyword or part number" name="ref" onchange="searchproductsphone(event)" autocomplete="off">
            <form action="/searchref" hidden class="hiddenformpc" method="post">
              {% csrf_token %}
              <input type="text" name="ref">
            </form>
            <!-- <button type="submit" class="mobile-search__button mobile-search__button--search searchbtn" onclick="searchproductsphone(event)">
              <svg width="20" height="20">
                <path d="M19.2,17.8c0,0-0.2,0.5-0.5,0.8c-0.4,0.4-0.9,0.6-0.9,0.6s-0.9,0.7-2.8-1.6c-1.1-1.4-2.2-2.8-3.1-3.9C10.9,14.5,9.5,15,8,15
    c-3.9,0-7-3.1-7-7s3.1-7,7-7s7,3.1,7,7c0,1.5-0.5,2.9-1.3,4c1.1,0.8,2.5,2,4,3.1C20,16.8,19.2,17.8,19.2,17.8z M8,3C5.2,3,3,5.2,3,8
    c0,2.8,2.2,5,5,5c2.8,0,5-2.2,5-5C13,5.2,10.8,3,8,3z"></path>
              </svg>
            </button> -->
            <div class="mobile-search__field"></div>
            <div class="phoneseggestions search__dropdown search__dropdown--suggestions suggestions " style="top: 3em;">
              <div class="d-flex justify-content-between">
              
                <div class="suggestions__group-title brands d-flex" style="width: 92%; overflow-x: scroll;">
                </div>
                <button class="p-2 text-white searchdropdownremover" style="background: red; width: 8%;" aria-hidden="true">
                  &times;
                </button>
              </div>
              <div class="suggestions__group">
                <div class="suggestions__group-title">Products</div>
                <div class="suggestions__group-content searchresults" style="height: 60vh; overflow-y: scroll;">

                </div>
              </div>

            </div>

          </div>
        </div>

        <div class="mobile-header__indicators">

          <div class="mobile-indicator mobile-indicator--search d-md-none">
            <button type="button" class="mobile-indicator__button">
              <span class="mobile-indicator__icon">
                <svg width="20" height="20">
                  <path d="M19.2,17.8c0,0-0.2,0.5-0.5,0.8c-0.4,0.4-0.9,0.6-0.9,0.6s-0.9,0.7-2.8-1.6c-1.1-1.4-2.2-2.8-3.1-3.9C10.9,14.5,9.5,15,8,15
    c-3.9,0-7-3.1-7-7s3.1-7,7-7s7,3.1,7,7c0,1.5-0.5,2.9-1.3,4c1.1,0.8,2.5,2,4,3.1C20,16.8,19.2,17.8,19.2,17.8z M8,3C5.2,3,3,5.2,3,8
    c0,2.8,2.2,5,5,5c2.8,0,5-2.2,5-5C13,5.2,10.8,3,8,3z"></path>
                </svg>
              </span>
            </button>
          </div>
          {% if  user.groups.all.0.name != 'admin' %}
          <!-- account icon
          <div class="mobile-indicator d-block">
            <a href="#" class="mobile-indicator__button">
              <span class="mobile-indicator__icon">
                <svg width="20" height="20">
                  <path d="M20,20h-2c0-4.4-3.6-8-8-8s-8,3.6-8,8H0c0-4.2,2.6-7.8,6.3-9.3C4.9,9.6,4,7.9,4,6c0-3.3,2.7-6,6-6s6,2.7,6,6
    c0,1.9-0.9,3.6-2.3,4.7C17.4,12.2,20,15.8,20,20z M14,6c0-2.2-1.8-4-4-4S6,3.8,6,6s1.8,4,4,4S14,8.2,14,6z"></path>
                </svg>
              </span>
            </a>
          </div>-->
          <div class="me-5 d-flex align-items-center">

            {% if user.groups.all.0.name == 'clients'%}
            <input type="hidden" class="clientid" name="clientid" value="{{user.client.id}}">
            <div hidden class="clientidholder border rounded p-2" clientid="{{user.client.id}}">
            </div>
            <input type="hidden" class="cmndfromclient" name="clientid" value="true">
            {% else %}
            <div  class="clientidholder border rounded p-2" clientid="">
            </div>

            <input type="hidden" class="cmndfromclient" value="false">

            {% endif %}
            <button class="btn bg-orange text-white me-2" onclick="validercmdinheader(event)" style="border-radius:14px;">Valider</button>
          </div>
          <div class="mobile-indicator"><a href="/cart" target="_blank" class="mobile-indicator__button"><span class="mobile-indicator__icon bi bi-cart text-white me-5" style="font-size:20px;"><span class="mobile-indicator__counter commanditems"></span></span></a></div>
          <!-- <div class="indicator indicator--trigger--click">
            <a href="{% url 'main:cart' %}" target="_blank">
              <div class="input-group">
                <span class="input-group-text" id="basic-addon1">
                  <span class="badge bg-danger rounded-pill commanditems">0</span>
                  <svg width="20" height="20">
                    <circle cx="7" cy="17" r="2"></circle>
                    <circle cx="15" cy="17" r="2"></circle>
                    <path d="M20,4.4V5l-1.8,6.3c-0.1,0.4-0.5,0.7-1,0.7H6.7c-0.4,0-0.8-0.3-1-0.7L3.3,3.9C3.1,3.3,2.6,3,2.1,3H0.4C0.2,3,0,2.8,0,2.6
      V1.4C0,1.2,0.2,1,0.4,1h2.5c1,0,1.8,0.6,2.1,1.6L5.1,3l2.3,6.8c0,0.1,0.2,0.2,0.3,0.2h8.6c0.1,0,0.3-0.1,0.3-0.2l1.3-4.4
      C17.9,5.2,17.7,5,17.5,5H9.4C9.2,5,9,4.8,9,4.6V3.4C9,3.2,9.2,3,9.4,3h9.2C19.4,3,20,3.6,20,4.4z"></path>
                  </svg>
                </span>

              </div>
            </a>

          </div> -->
          {% endif %}
        </div>
        {% endif %}
      </div>
    </div>
  </header>
  <script>
    // $(window).on('click', (e)=>{
    //   console.log($(e.target).hasClass('mobile-search__input'))
    //   if ($(e.target).hasClass('mobile-search__input')) {
    //     $('.phoneseggestions').addClass('search__dropdown--open')
    //   }else{
    //     $('.phoneseggestions').removeClass('search__dropdown--open')
    //   }
    // })
  </script>

ibra/templates/proccesslyt.html
{% load static %}
<!DOCTYPE html>

<html dir="ltr" lang="en">

<head>
    <meta charset="utf-8" />
    <meta content="width=device-width,initial-scale=1" name="viewport" />
    <meta content="telephone=no" name="format-detection" />
    {% block meta %}
    {% endblock %}
    {% if title %}
    <title>Autoparts - {{titla}} </title>
    {% else %}
    <title>Autoparts - Choose items</title>
    {% endif %}
    <link href="images/favicon.png" rel="icon" type="image/png" /><!-- fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i" rel="stylesheet" />
    <!-- css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link href="{% static 'css/bootstrap.css' %} " rel="stylesheet" />
    <link href="{% static 'css/owl.carousel.min.css'  %} " rel="stylesheet" />
    <link href="{% static 'css/photoswipe.css'%} " rel="stylesheet" />
    <link href="{% static 'css/default-skin.css'%} " rel="stylesheet" />
    <link href="{% static 'css/select2.min.css'%} " rel="stylesheet" />
    <link href="{% static 'css/style.css'%} " rel="stylesheet" />
    <link href="{% static 'css/style.header-spaceship-variant-one.css'%} " rel="stylesheet" />
    <link href="{% static 'css/style.mobile-header-variant-one.css'%} " rel="stylesheet" />
    <script src="{% static 'js/jquery.min.js'%}"></script>
</head>
<body>
    <div class="site__body">
        <div class="block-header block-header--has-breadcrumb block-header--has-title">
            <div class="container">
                <div class="block-header__body">
                    <nav class="breadcrumb block-header__breadcrumb" aria-label="breadcrumb">
                        <ol class="breadcrumb__list">
                            <li class="breadcrumb__spaceship-safe-area" role="presentation"></li>
                            <li class="breadcrumb__item breadcrumb__item--parent breadcrumb__item--first"><a
                                    href="index.html" class="breadcrumb__item-link">Home</a></li>
                            <li class="breadcrumb__item breadcrumb__item--parent"><a href=""
                                    class="breadcrumb__item-link">Breadcrumb</a></li>
                            <li class="breadcrumb__item breadcrumb__item--current breadcrumb__item--last"
                                aria-current="page"><span class="breadcrumb__item-link">Current Page</span></li>
                            <li class="breadcrumb__title-safe-area" role="presentation"
                                style="--block-header-title-width:219.5px;"></li>
                        </ol>
                    </nav>
                    <h1 class="block-header__title">Transmission</h1>
                </div>
            </div>
        </div>
        <div class="block-split block-split--has-sidebar">
            <div class="container">
                <div class="block-split__row row no-gutters">
                    
                    <div class="block-split__item block-split__item-content col-auto">
                        <div class="block">
                            <div class="products-view">
                                
                                {% block pcontent %}
                                    
                                {% endblock %}

                            </div>
                        </div>
                    </div>
                </div>
                <div class="block-space block-space--layout--before-footer"></div>
            </div>
        </div>
    </div>
</body>